# Generated by Django 5.2.7 on 2025-11-20 19:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(default=datetime.datetime.now, max_length=100)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('password_hash', models.CharField(default='', max_length=100)),
                ('remember_token', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.users')),
                ('advancedCalorieTable', models.FloatField(default=0)),
            ],
            bases=('dashboard.users',),
        ),
        migrations.CreateModel(
            name='regularUser',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.users')),
                ('streak', models.IntegerField(default=0)),
                ('weight_kg', models.FloatField(default=0)),
                ('heigh_cm', models.FloatField(default=0)),
                ('last_logged', models.DateField(default=datetime.datetime.now)),
            ],
            bases=('dashboard.users',),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('mode', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home')], default='gym', max_length=10)),
                ('streak', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
