# Generated by Django 5.2.7 on 2026-02-01 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrition',
            options={},
        ),
        migrations.RemoveField(
            model_name='logfood',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='created_at',
        ),
        migrations.AddField(
            model_name='logfood',
            name='food',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutrition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logfood',
            name='grams',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logfood',
            name='meal_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
