# Generated by Django 5.2.7 on 2026-02-01 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlogs',
            name='exercise',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutlogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('mode', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home')], max_length=10)),
                ('plan_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='exercise.workoutplanexercise')),
            ],
        ),
    ]
