# Generated by Django 5.2.7 on 2026-02-01 17:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_workoutlogs_exercise_alter_workoutlogs_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutLogs',
            new_name='WorkoutLog',
        ),
    ]
