# Generated by Django 5.2.7 on 2026-02-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_rename_workoutlogs_workoutlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='calories_burned',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='duration_min',
        ),
    ]
