# Generated by Django 5.2.7 on 2026-02-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_remove_workoutlog_calories_burned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='exercise',
        ),
    ]
