# Generated by Django 5.2.7 on 2026-02-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_remove_workoutlog_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='logged_at',
        ),
    ]
