# Generated by Django 5.2.7 on 2026-02-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_remove_workoutlog_logged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
