# Generated by Django 5.2.7 on 2026-02-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_workoutlog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
    ]
