# Generated by Django 5.2.7 on 2026-02-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_workoutlog_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
